blank_issues_enabled: false
contact_links:
  - name: Ask a question about the book or start a discussion
    url: https://github.com/jobovy/galaxiesbook-forum/discussions
    about: Ask and answer galaxiesbook related questions